/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "Errors_constants.h"

namespace evernote { namespace edam {

const ErrorsConstants g_Errors_constants;

ErrorsConstants::ErrorsConstants() {
}

}} // namespace

