/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "NoteStore_constants.h"

namespace evernote { namespace edam {

const NoteStoreConstants g_NoteStore_constants;

NoteStoreConstants::NoteStoreConstants() {
}

}} // namespace

