/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Types_CONSTANTS_H
#define Types_CONSTANTS_H

#include "Types_types.h"

namespace evernote { namespace edam {

class TypesConstants {
 public:
  TypesConstants();

  std::string EDAM_NOTE_SOURCE_WEB_CLIP;
  std::string EDAM_NOTE_SOURCE_MAIL_CLIP;
  std::string EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY;
};

extern const TypesConstants g_Types_constants;

}} // namespace

#endif
